### ISSUE TITLE
playlist.py fails on the port portion of the call to mpd

### ISSUE THREAD

**Issue by iconoclasthero** [bonelifer/mpd-scripts#21]
```
$ ./playlist.py 
Traceback (most recent call last):
  File "/dev/shm/cache/./playlist.py", line 107, in <module>
    main()
  File "/dev/shm/cache/./playlist.py", line 104, in main
    view_playlist(10)
  File "/dev/shm/cache/./playlist.py", line 93, in view_playlist
    client = connect_mpd(mpd_config.get('192.168.1.2'), int(mpd_config.get('6600')), mpd_config.get('hard-coded password', ''))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by iconoclasthero** [comment]
It was also failing on the password too, but i hardcoded everything and once the port is fixed, the rest of the script can be tested.
